const STORAGE_KEY='college-path-planner-demo-v1';
const state={plan:loadPlan()};
const schools=[
 {name:'Metro Tech University',type:'Large university',strength:'Engineering / Technology',admitGpa:4.15,admitSat:1380,cost:'medium'},
 {name:'State Research University',type:'Large university',strength:'Health / Life Sciences',admitGpa:3.9,admitSat:1280,cost:'low'},
 {name:'Innovation Polytechnic',type:'Mid-size university',strength:'Engineering / Technology',admitGpa:3.75,admitSat:1210,cost:'medium'},
 {name:'Riverside College',type:'Small college',strength:'Undecided / Explore',admitGpa:3.45,admitSat:1120,cost:'medium'},
 {name:'Capital Public University',type:'Large university',strength:'Business / Entrepreneurship',admitGpa:3.55,admitSat:1160,cost:'low'},
 {name:'Coastal Science Institute',type:'Mid-size university',strength:'Health / Life Sciences',admitGpa:3.65,admitSat:1200,cost:'high'}
];
const els={form:document.getElementById('plannerForm'),sampleBtn:document.getElementById('sampleBtn'),notice:document.getElementById('notice'),empty:document.getElementById('emptyState'),result:document.getElementById('result'),readiness:document.getElementById('readiness'),posture:document.getElementById('posture'),readinessBadge:document.getElementById('readinessBadge'),majors:document.getElementById('majors'),collegeCards:document.getElementById('collegeCards'),funding:document.getElementById('funding'),nextAction:document.getElementById('nextAction'),whyAction:document.getElementById('whyAction'),schoolCount:document.getElementById('schoolCount'),taskCount:document.getElementById('taskCount'),fundingCount:document.getElementById('fundingCount'),priorityMetric:document.getElementById('priorityMetric'),taskList:document.getElementById('taskList'),activityLog:document.getElementById('activityLog'),resetBtn:document.getElementById('resetBtn')};
function loadPlan(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||null}catch{return null}}
function savePlan(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.plan))}
function input(){return{gpa:+document.getElementById('gpa').value,sat:+document.getElementById('sat').value,advanced:+document.getElementById('advanced').value,interest:document.getElementById('interest').value,environment:document.getElementById('environment').value,cost:document.getElementById('cost').value,goals:document.getElementById('goals').value.trim()}}
function readiness(p){let s=40;s+=Math.min(24,Math.max(0,(p.gpa-3)*14));s+=Math.min(20,Math.max(0,(p.sat-900)/25));s+=Math.min(16,p.advanced*1.6);return Math.round(Math.max(0,Math.min(100,s)))}
function majorPaths(interest){const map={
 'Engineering / Technology':['Biomedical Engineering','Mechanical Engineering','Computer Science','Engineering Exploratory'],
 'Health / Life Sciences':['Biology','Neuroscience','Public Health','Biomedical Sciences'],
 'Business / Entrepreneurship':['Business Analytics','Finance','Marketing','Entrepreneurship'],
 'Arts / Design':['UX / Product Design','Digital Media','Architecture','Visual Communication'],
 'Public Service':['Public Policy','Criminal Justice','Political Science','Emergency Management'],
 'Undecided / Explore':['Exploratory Studies','Data + Society','Interdisciplinary Science','Business Foundations']};return map[interest]||map['Undecided / Explore']}
function matchSchool(p,s){let points=50;points+=(p.gpa-s.admitGpa)*20;points+=(p.sat-s.admitSat)/20;if(s.strength===p.interest)points+=10;if(s.type===p.environment||p.environment==='No strong preference')points+=5;if(p.cost==='high'&&s.cost==='low')points+=8;if(p.cost==='high'&&s.cost==='high')points-=8;const score=Math.round(Math.max(1,Math.min(99,points)));let band='Reach';if(score>=66)band='Likely';else if(score>=48)band='Target';return{...s,score,band,why:`${s.strength===p.interest?'Academic strength aligns with stated interest.':'Adds breadth beyond the primary interest.'} ${s.type===p.environment?'Environment matches preference.':'Environment fit should be verified.'}`}}
function fundingPriorities(p){const items=['Complete the official FAFSA as soon as the cycle opens.','Build a scholarship list with eligibility, deadline, award amount, and source link.'];if(p.cost==='high')items.push('Prioritize net-price comparison and in-state/public options before judging sticker price.');else items.push('Compare merit aid and departmental scholarships alongside total cost.');items.push('Verify any military, state, employer, or family-specific education benefits with the official program source.');return items}
function buildPlan(p){const r=readiness(p);const matches=schools.map(s=>matchSchool(p,s)).sort((a,b)=>b.score-a.score);const counts={reach:matches.filter(x=>x.band==='Reach').length,target:matches.filter(x=>x.band==='Target').length,likely:matches.filter(x=>x.band==='Likely').length};let posture='Build a balanced list';if(r>=82)posture='Strong academic position';else if(r<65)posture='Strengthen + diversify';const tasks=[{text:'Create a balanced reach / target / likely school list',done:false},{text:'Verify major requirements at top three schools',done:false},{text:'Create scholarship + aid tracker',done:false},{text:'Draft activities / accomplishments inventory',done:false},{text:'Map application and financial-aid deadlines',done:false}];let next='Build a balanced initial school list';let why=`The model currently sees ${counts.reach} reach, ${counts.target} target, and ${counts.likely} likely options in the sample set. Establishing the list creates the base for deadline, cost, and scholarship work.`;if(p.cost==='high'){next='Build a net-price and funding comparison';why='Cost sensitivity is marked very important, so affordability needs to be evaluated early rather than after applications are submitted.'}if(r<65){next='Identify the highest-impact profile improvement';why='The current readiness score suggests that strengthening testing, course rigor, essays, or school-list breadth may improve outcomes before adding more applications.'}return{profile:p,readiness:r,posture,majors:majorPaths(p.interest),matches,funding:fundingPriorities(p),tasks,next,why,createdAt:new Date().toISOString()}}
function render(){const plan=state.plan;if(!plan)return;els.empty.hidden=true;els.result.hidden=false;els.readiness.textContent=`${plan.readiness}/100`;els.posture.textContent=plan.posture;els.readinessBadge.textContent=plan.readiness>=80?'Strong':plan.readiness>=65?'Developing':'Needs focus';els.readinessBadge.className=`badge ${plan.readiness>=80?'success':'warning'}`;els.majors.innerHTML=plan.majors.map(x=>`<span class="chip">${x}</span>`).join('');els.collegeCards.innerHTML=plan.matches.slice(0,5).map(x=>`<div class="college-card"><strong><span>${x.name}</span><span>${x.band} · ${x.score}</span></strong><p>${x.why}</p></div>`).join('');els.funding.innerHTML=plan.funding.map(x=>`<li>${x}</li>`).join('');els.nextAction.textContent=plan.next;els.whyAction.textContent=plan.why;renderTasks();els.schoolCount.textContent=plan.matches.length;els.fundingCount.textContent=plan.funding.length;els.priorityMetric.textContent=plan.next.split(' ').slice(0,3).join(' ')}
function renderTasks(){if(!state.plan)return;els.taskList.innerHTML=state.plan.tasks.map((t,i)=>`<div class="task"><label><input type="checkbox" data-task="${i}" ${t.done?'checked':''}/> <span>${t.text}</span></label><span>${t.done?'Verified':'Open'}</span></div>`).join('');const done=state.plan.tasks.filter(t=>t.done).length;els.taskCount.textContent=`${done}/${state.plan.tasks.length}`;document.querySelectorAll('[data-task]').forEach(box=>box.addEventListener('change',e=>{const i=+e.target.dataset.task;state.plan.tasks[i].done=e.target.checked;savePlan();addActivity(`${e.target.checked?'Completed':'Reopened'}: ${state.plan.tasks[i].text}`);renderTasks()}))}
function addActivity(msg){const li=document.createElement('li');li.textContent=`${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} — ${msg}`;els.activityLog.prepend(li)}
els.form.addEventListener('submit',e=>{e.preventDefault();state.plan=buildPlan(input());savePlan();render();els.notice.textContent='Path generated. Recommendations are demo guidance and should be verified with current official sources.';addActivity(`Plan generated at ${state.plan.readiness}/100 readiness.`)});
els.sampleBtn.addEventListener('click',()=>{document.getElementById('gpa').value='4.18';document.getElementById('sat').value='1320';document.getElementById('advanced').value='9';document.getElementById('interest').value='Engineering / Technology';document.getElementById('environment').value='Large university';document.getElementById('cost').value='high';document.getElementById('goals').value='I want strong engineering options, internships, manageable cost, and flexibility to explore biomedical engineering or adjacent technical majors.';els.notice.textContent='Fictional sample loaded. Change anything you want.'});
els.resetBtn.addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);state.plan=null;els.form.reset();els.result.hidden=true;els.empty.hidden=false;els.readinessBadge.textContent='Waiting';els.readinessBadge.className='badge muted';els.schoolCount.textContent='0';els.taskCount.textContent='0/5';els.fundingCount.textContent='0';els.priorityMetric.textContent='—';els.taskList.innerHTML='';els.activityLog.innerHTML='<li>Planner initialized.</li>';els.notice.textContent='Demo reset.'});
if(state.plan)render();